name: Open an issue
description: |
 Report a bug with RetroPie-Setup scripts
body:

  - type: markdown
    id: info
    attributes:
     label: Important
     value: |
       **Only** RetroPie-Setup bugs should be reported here.
       The **[RetroPie forums](https://retropie.org.uk/forum)** should be used used for any other question/support request.
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description of the bug
    validations:
      required: true

